name: cloudflare-dev

on:
  push:
    branches:
      - develop

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Publish to Cloudflare
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: pages deploy ./dist --project-name=tpa-roadmap-dev
    - name: print deployment-url
      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
      run: echo $DEPLOYMENT_URL