name: cloudflare-dev

on:
  push:
    branches:
      - develop

env:
  PUBLIC_API_URL: "https://api.roadmap.sh"
  PUBLIC_EDITOR_APP_URL: "https://draw.roadmap.sh"
  PUBLIC_AVATAR_BASE_URL: "https://dodrc8eu8m09s.cloudfront.net/avatars"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        check-latest: true

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Publish to Cloudflare
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: pages deploy ./dist --project-name=tpa-roadmap-dev
    - name: print deployment-url
      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
      run: echo $DEPLOYMENT_URL